openapi: 3.0.0
info:
  title: Test file example id
  version: "1"
servers:
  - url: /api
paths:
  /test:
    get:
      operationId: File
      responses:
        "200":
          description: thing
          content:
            "*/*":
              schema:
                type: string
          examples:
            application/json:
              id: 12345
